version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ativflow_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DEBUG: "True"
      SECRET_KEY: your-secret-key-change-in-production
      DATABASE_URL: postgresql://user:password@db:5432/ativflow_db
      FRONTEND_URL: http://localhost:5173
      STORAGE_PROVIDER: local
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads

volumes:
  db_data:

